server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://wallet-db:5432/skillmatch_wallets
    username: skillmatch
    password: skillmatch
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: skillmatch
    password: skillmatch

logging:
  level:
    org.springframework.amqp: DEBUG
    org.springframework.rabbit: DEBUG